package com.goraksh.rest.auth.request;

import com.goraksh.rest.RandomString;

public class AuthorisationResponseGenerator {
	
	private AuthorisationRequest authRequest;
	private String state;
	private RandomString random;
	
	public AuthorisationResponseGenerator( AuthorisationRequest authReqest ) {
		this.authRequest = authReqest;
		this.random = RandomString.getInstance();
	}
	
	/**
	 * This constructor to be used, only when stae needs to be overriden over the initial state generated by the OAuthStartServlet.
	 * Under all practical conditions, this constructor should never be used
	 * 
	 * @param authReqest
	 * @param state
	 */
	public AuthorisationResponseGenerator( AuthorisationRequest authReqest, String state ) {
		this(authReqest);
		this.state = state;			
	}
	
	public AuthorisationResponse authorisationGrantReponse() {
		String code = random.nextString();
		String state = this.state != null ? this.state :  this.authRequest.getState();
		AuthorisationResponse authResponse = new AuthorisationResponse( code, state, authRequest.getResponseType() );
		System.out.println("New Authorisation response Generated for 'Respose_type=code' for State: " + authResponse.getState() + " .Authorisation Response: " + authResponse.toString() );
		return authResponse;		
	}
	
	public AuthorisationResponse implicitGrantResponse() {
		String code = random.nextString();
		String state = this.state != null ? this.state :  this.authRequest.getState();
		AuthorisationResponse authResponse = new AuthorisationResponse( code, state, authRequest.getResponseType() );
		System.out.println("New Authorisation response Generated 'Respose_type=token' for State: " + authResponse.getState() + " .Authorisation Response: " + authResponse.toString() );
		return authResponse;		
	}

}
